### PR TITLE
UI Redesign for Select, Index, and Admin Pages

### PR DESCRIPTION
**Pull request by birm**

### CODE REVIEW

**Comment by ajasniew** [comment]
UI redesign of admin pages  doesn't contain the Manage Superusers For caMic Lymphocyte App functionality (already in the release branch), which allow add and remove superusers for caMic Lymphocyte App.  This functionality is necessary to switch user by lymph app superusers.

The Lymphocyte App won't work without this functionality.

Code CAN NOT be merged.

**Comment by birm** [comment]
Thank you, I'll work on it -#49

**Comment by birm** [comment]
@ajasniew I've done a redesign, but I can't really test as my dev environment doesn't have Lymphocyte; I get "The requested URL /camicroscope/api/Data/lymphocyteSuperusers.php was not found on this server."

I think you'll have to help me test or test yourself.

**Comment by birm** [comment]
done, pending testing, with ad6c00a865ebea7d157c8b04de1058e306037944

**Comment by ajasniew** [comment]
Thank you, Ryan.  
I tested your new design of the Lymphocyte App Superusers and implemented small fixes.
https://github.com/camicroscope/Security/pull/47/commits/bd6619868a14e3104cf11b2749782f1c72d31c7c

**Pull request merged**
