### PR TITLE
Update UI for camic release branch

### PR DESCRIPTION
**Pull request by birm**

### CODE REVIEW

**Comment by lastlegion** [comment]
Some styling issues:
image
I'm running this behind a reverse proxy

**Comment by lastlegion** [comment]
There are still some absolute links, like the form submission

**Comment by lastlegion** [comment]
There is a SEND text instead of the icon while uploading images

**Comment by birm** [comment]
This seems to be a result of "Mixed Content: The page at 'https://wolf.cci.emory.edu/camic_distro1/select.php' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/icon?family=Material+Icons'. This request has been blocked; the content must be served over HTTPS." To fix this, I've added icons.css to the repo in 
 ee616da

**Comment by lastlegion** [comment]
Merged locally.

**Pull request closed without merging**
