### PR TITLE
Emory dev into Dev (2 Feb)

### PR DESCRIPTION
**Pull request by birm**
I should've done this in smaller increments. As far as I can tell, the big changes here are

-  Session Expiration Automatic Renewal and Notifications
-  Centralized data/yaml (currently) driven customizations

### CODE REVIEW

**Comment by birm** [comment]
See #51

**Comment by birm** [comment]
after this, I plan to use develop instead of emory-dev for harmony

**Comment by tdiprima** [comment]
@birm merge complete.  Can `emory-dev` be removed?

**Comment by birm** [comment]
Yes, doing so now.

**Pull request merged**
